<a href="https://colab.research.google.com/github/Husseinmdarman/AI_core_practicals/blob/main/Numpy_intro_and_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy intro

In [69]:
!pip install numpy

In [70]:
import numpy as np

## Q1. Create a NumPy array with 5 elements of your choice.

In [71]:
np.array([1,3,4,5,6])

array([1, 3, 4, 5, 6])

In [72]:
array = np.array([1,3,4,5,6])

## Q2. Display the 5th element of the array

In [73]:
array[4]

6

## Q3. Use the np.random.randint function to create a 2D array of size (3,4) with random integers between 0 and 10.

In [74]:
np.random.randint(low= 0, high = 10, size= (3,4))

array([[7, 7, 4, 4],
       [9, 2, 8, 8],
       [1, 1, 4, 8]])

## Q4. Create a NumPy array of random numbers with dimensions 6 x 10. Call it my_array

In [75]:
my_array = np.random.randn(6,10)
my_array

array([[ 0.66737786,  0.54637191,  0.97282251,  1.54873228,  0.54537114,
        -1.63426709,  0.19452759,  0.14244537,  0.78708465,  0.17519824],
       [ 1.5135298 , -1.26696724,  1.54122041,  0.74596116, -1.22142673,
         0.11794359,  0.52765757, -0.27518094, -0.98466384,  0.20837975],
       [-0.53587108,  1.49217277, -0.89667372, -1.79275219,  2.14946301,
         0.81332733,  0.3690616 , -0.60022435, -0.29490472, -0.60740672],
       [-1.06716591, -0.02900908,  1.1455026 ,  0.01793096, -0.75134042,
         0.39313952,  1.28346082,  0.55257554,  2.32470341, -0.8952156 ],
       [ 0.43195728,  1.10743654,  1.68321035, -0.73942974,  0.14335289,
         0.37483957,  0.72990169, -1.86543214, -0.30698618,  0.38006763],
       [-1.33930611,  0.94999232,  0.55669326,  0.1110874 ,  0.01588496,
        -0.9700614 ,  2.68347613, -1.43986633,  0.3913273 ,  1.62931699]])

## Q5. Slice out the 1st, 3rd and 5th column of the array into as new array. Call it new_array

In [76]:
new_array = my_array[:, (0,2,4)]

## Q6. Print the shape of each array you have created.

In [77]:
print(new_array.shape)
print(my_array.shape)

(6, 3)
(6, 10)


## Q7. Try to multiply my_array x new_array. Does it work? If not, do you know why?

In [78]:
my_array * new_array

ValueError: ignored

The operands are in different shapes therefore cannot be multipled together since the inner dimensionality need to be the same


## Q8. Transpose new_array and try again. Does it work now?

In [94]:
new_array_t = new_array.T
new_array_t.shape
my_array * new_array_t

ValueError: ignored

## Q9. Create a NumPy array of dimensions 5 x 5 where each element is a zero.

In [112]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [113]:
array = np.zeros((5,5))

## Q10. Replace the left diagonal of the array with 1s.

In [117]:
new_values = np.array([1,1,1,1])

In [116]:
array.shape

(5, 5)

In [118]:
diagonal_indices = np.arange(1, array.shape[0])
array[diagonal_indices, diagonal_indices - 1] = new_values

In [119]:
array

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

## Q11. Create a 3D array of size (3,4,5) and use slicing to select the first two elements of the last dimension.

In [87]:
three_dim_array = np.random.randn(3,4,5)
three_dim_array

array([[[-2.12134144, -1.2839279 ,  0.51140207,  1.1237433 ,
          2.62424348],
        [-0.41388733, -3.78742852,  0.06892128,  0.66527465,
          0.48708284],
        [ 0.48864506, -0.05198404,  1.61558147, -0.26036143,
         -0.16146156],
        [-0.7819162 , -0.57897946, -0.59098396, -0.02080128,
         -0.32361645]],

       [[ 0.07373768,  1.44510588,  1.03574162,  0.45706309,
          0.31685863],
        [-0.61787175, -1.75648734,  0.82456658, -0.62050271,
          0.35772386],
        [-0.71826092, -0.12068753, -0.05883413, -0.38262179,
          0.52579755],
        [ 0.90088368,  1.74973822,  0.80585195,  2.11432609,
          1.56968543]],

       [[-2.13653459,  1.33797485,  0.23354344,  0.92275183,
         -0.65859801],
        [ 1.26044538,  0.13779486,  1.3947719 , -0.96521697,
          0.27904097],
        [ 0.69050369, -0.09660196,  1.18632863, -0.52196809,
         -0.02088341],
        [-0.42984227, -0.72178712,  0.07819376,  0.72727713,
         -0

In [88]:
three_dim_array[2:]

array([[[-2.13653459,  1.33797485,  0.23354344,  0.92275183,
         -0.65859801],
        [ 1.26044538,  0.13779486,  1.3947719 , -0.96521697,
          0.27904097],
        [ 0.69050369, -0.09660196,  1.18632863, -0.52196809,
         -0.02088341],
        [-0.42984227, -0.72178712,  0.07819376,  0.72727713,
         -0.2022363 ]]])

In [89]:
three_dim_array[2:, 3:]

array([[[-0.42984227, -0.72178712,  0.07819376,  0.72727713,
         -0.2022363 ]]])

In [90]:
three_dim_array[2:,3:,0:2]

array([[[-0.42984227, -0.72178712]]])

## Q12. Create a NumPy 1D-array with 10 elements, then reshape the array into a 2x5 matrix.

In [122]:
reshaped_array = np.random.rand(10).reshape(2,5)

## Q13.Create a second NumPy array with 5 elements, and join it to the first array using the concatenate function.

In [144]:
secondary_array = np.random.rand(1,5)
secondary_array

array([[0.31955019, 0.53217633, 0.60562219, 0.12355545, 0.22437007]])

In [149]:
np.concatenate((secondary_array,reshaped_array), axis= 0)

array([[0.31955019, 0.53217633, 0.60562219, 0.12355545, 0.22437007],
       [0.08556691, 0.95773113, 0.96652173, 0.50827109, 0.24613271],
       [0.14699175, 0.80566354, 0.91730196, 0.23538676, 0.77932651]])

## Q14.Create two arrays of size (2,3) and broadcast them together to create an array of size (2,3,3).

In [153]:
array_1 = np.random.randn(2,3)
array_2 = np.random.randn(2,3)

In [160]:
broadcasted_array = array_1.reshape(-1,1,3) * array_2.reshape(2,-1,1)

In [162]:
print(broadcasted_array.shape)
broadcasted_array

(2, 3, 3)


array([[[-0.26029546,  0.08684727,  0.34997797],
        [-0.29003707,  0.09677052,  0.38996679],
        [ 1.35660871, -0.45263088, -1.82401633]],

       [[ 1.04506285,  1.03059189, -2.50787918],
        [-0.10215632, -0.10074176,  0.24514861],
        [ 0.58980749,  0.58164043, -1.41538464]]])